apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ax
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/ax/ax.git
  ref:
    branch: main
  secretRef:
    name: ax-git-credentials
