{{- if and .Values.postgresql.external.enabled .Values.postgresql.external.cloudSqlProxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ax.fullname" . }}-cloud-sql-proxy
  namespace: {{ include "ax.namespace" . }}
  labels:
    {{- include "ax.componentLabels" (dict "component" "cloud-sql-proxy" "context" $) | nindent 4 }}
  {{- with .Values.postgresql.external.cloudSqlProxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
