{{- if .Values.nats.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ax.fullname" . }}-nats-auth
  namespace: {{ include "ax.namespace" . }}
  labels:
    {{- include "ax.labels" . | nindent 4 }}
type: Opaque
stringData:
  host-password: {{ .Values.nats.config.authorization.users | first | dig "password" (randAlphaNum 32) | quote }}
  sandbox-password: {{ index .Values.nats.config.authorization.users 1 | dig "password" (randAlphaNum 32) | quote }}
{{- end }}
