apiVersion: v1
kind: Service
metadata:
  name: {{ include "ax.fullname" . }}-host
  namespace: {{ include "ax.namespace" . }}
  labels:
    {{- include "ax.componentLabels" (dict "component" "host" "context" $) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ax.selectorLabels" (dict "component" "host" "context" $) | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
