apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ax.fullname" . }}-pool-controller
  namespace: {{ include "ax.namespace" . }}
  labels:
    {{- include "ax.componentLabels" (dict "component" "pool-controller" "context" $) | nindent 4 }}
